[workspace]
authors = ["Tantely Hevitriniavo <tantely@vatilab.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "scrap_py"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
main = "pixi run python src/main.py"

[dependencies]
python = ">=3.13.5,<3.14"

[pypi-dependencies]
pytest = ">=8.4.1, <9"
botasaurus = ">=4.0.88, <5"
beautifulsoup4 = ">=4.13.5, <5"
requests = ">=2.32.5, <3"
xmltodict = ">=0.14.2, <0.15"
asyncio = ">=4.0.0, <5"
pandas = ">=2.3.2, <3"
